# Generated by Django 6.0.7 on 2026-08-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', help_text='Used to pick the assistant character (boy/girl).', max_length=10),
        ),
    ]
