"""PDF report generation for the AI assistant file reader.

Generates a clean, professional report of uploaded documents together
with the assistant's analysis, with full Arabic (RTL) support using the
Amiri font bundled with the project.
"""

import logging
from datetime import datetime

from django.conf import settings
from django.utils.translation import gettext_lazy as _

from .fileutils import human_size

logger = logging.getLogger(__name__)

try:
    import arabic_reshaper
    from bidi.algorithm import get_display
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )
except ImportError:  # pragma: no cover
    arabic_reshaper = None
    get_display = None
    pdfmetrics = None
    TTFont = None
    SimpleDocTemplate = None
    Paragraph = None
    Table = None
    TableStyle = None
    Spacer = None
    colors = None
    A4 = None
    mm = None
    ParagraphStyle = None
    getSampleStyleSheet = None
    TA_CENTER = TA_LEFT = TA_JUSTIFY = "left"

BRAND = "#4F46E5"
BRAND_DARK = "#3730A3"
INK = "#111827"
MUTED = "#6B7280"
LINE = "#E5E7EB"
BG = "#F8FAFC"

_PRIMARY_FONT = "Helvetica"
_BOLD_FONT = "Helvetica-Bold"


def _fonts_dir():
    for base in (settings.BASE_DIR, settings.BASE_DIR / "staticfiles"):
        candidate = base / "static" / "fonts"
        if candidate.exists():
            return candidate
        candidate = base / "fonts"
        if candidate.exists():
            return candidate
    candidate = settings.BASE_DIR / "static" / "fonts"
    if candidate.exists():
        return candidate
    return None


def _register_fonts():
    """Register the bundled Amiri font. Falls back to Helvetica."""
    global _PRIMARY_FONT, _BOLD_FONT

    if TTFont is None:
        return

    fonts_dir = _fonts_dir()

    if fonts_dir is None:
        return

    regular = fonts_dir / "Amiri-Regular.ttf"
    bold = fonts_dir / "Amiri-Bold.ttf"

    try:
        pdfmetrics.registerFont(TTFont("Amiri", str(regular)))
        if bold.exists():
            pdfmetrics.registerFont(TTFont("Amiri-Bold", str(bold)))
        else:
            pdfmetrics.registerFont(TTFont("Amiri-Bold", str(regular)))
        _PRIMARY_FONT = "Amiri"
        _BOLD_FONT = "Amiri-Bold"
    except Exception as exc:  # pragma: no cover
        logger.warning("Could not register Amiri font: %s", exc)


def _has_arabic(text):
    return any("\u0600" <= char <= "\u06FF" for char in text)


def _arabic(text):
    """Shape and reorder text for correct Arabic rendering."""
    if not text:
        return text
    text = str(text)
    if not _has_arabic(text):
        return text
    if arabic_reshaper is None or get_display is None:
        return text
    reshaped = arabic_reshaper.reshape(text)
    return get_display(reshaped)


def _doc_title():
    return _("AI Assistant Document Report")


def _status_badge_label(kind):
    labels = {
        "pdf": "PDF",
        "docx": "Word",
        "xlsx": "Excel",
        "text": _("Text"),
        "image": _("Image"),
        "other": _("File"),
    }
    return labels.get(kind, kind.upper())


def _footer(canvas, document):
    canvas.saveState()

    width, height = A4

    canvas.setStrokeColor(LINE)
    canvas.setLineWidth(0.5)
    canvas.line(20 * mm, 18 * mm, width - 20 * mm, 18 * mm)

    canvas.setFont(_PRIMARY_FONT, 8)
    canvas.setFillColor(MUTED)
    canvas.drawString(
        20 * mm,
        14 * mm,
        _arabic(f"SchoolPlatform — {_('Generated by the AI Assistant')}"),
    )
    canvas.drawRightString(
        width - 20 * mm,
        14 * mm,
        f"{document.page}",
    )

    canvas.restoreState()


def _header(canvas, document):
    canvas.saveState()

    width, height = A4

    canvas.setFillColor(BRAND)
    canvas.rect(0, height - 30 * mm, width, 30 * mm, stroke=0, fill=1)

    canvas.setFillColor(colors.white)
    canvas.setFont(_BOLD_FONT, 16)
    canvas.drawString(
        20 * mm,
        height - 17 * mm,
        _arabic(_doc_title()),
    )

    canvas.setFont(_PRIMARY_FONT, 9)
    canvas.setFillColor(colors.HexColor("#E0E7FF"))
    canvas.drawRightString(
        width - 20 * mm,
        height - 17 * mm,
        "SchoolPlatform",
    )

    canvas.restoreState()


def _on_page(canvas, document):
    """Draw header + footer on every page."""
    _header(canvas, document)
    _footer(canvas, document)


def build_report(stream, *, institution, user_name, title=None,
                 generated_at=None, files=None, notes=None,
                 language=None):
    """Write a PDF report into ``stream`` (a binary file-like object).

    Arguments:
        institution: display name of the school/institution (or None).
        user_name:   name of the user who requested the report.
        title:       optional custom report title.
        generated_at: datetime object (defaults to now).
        files:       list of dicts with keys
                     {name, kind, size, excerpt} (or None).
        notes:       optional assistant analysis text.
        language:    "ar" or "en" (defaults to Django active language).
    """
    if SimpleDocTemplate is None:  # pragma: no cover
        raise RuntimeError("reportlab is not installed on this server.")

    _register_fonts()

    now = generated_at or datetime.now()
    language = language or "ar"

    styles = getSampleStyleSheet()

    h1 = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontName=_BOLD_FONT,
        fontSize=20,
        leading=26,
        textColor=INK,
        spaceAfter=2 * mm,
    )
    sub = ParagraphStyle(
        "ReportSub",
        parent=styles["Normal"],
        fontName=_PRIMARY_FONT,
        fontSize=10,
        leading=15,
        textColor=MUTED,
        spaceAfter=6 * mm,
    )
    h2 = ParagraphStyle(
        "ReportH2",
        parent=styles["Heading2"],
        fontName=_BOLD_FONT,
        fontSize=13,
        leading=18,
        textColor=BRAND_DARK,
        spaceBefore=5 * mm,
        spaceAfter=3 * mm,
    )
    body = ParagraphStyle(
        "ReportBody",
        parent=styles["Normal"],
        fontName=_PRIMARY_FONT,
        fontSize=10.5,
        leading=17,
        textColor=INK,
        alignment=TA_JUSTIFY,
        spaceAfter=3 * mm,
    )
    excerpt = ParagraphStyle(
        "ReportExcerpt",
        parent=body,
        fontSize=9.5,
        leading=15,
        textColor=MUTED,
        backColor=BG,
        borderColor=LINE,
        borderWidth=0.5,
        borderPadding=6,
    )
    cell = ParagraphStyle(
        "ReportCell",
        parent=styles["Normal"],
        fontName=_PRIMARY_FONT,
        fontSize=9.5,
        leading=13,
        textColor=INK,
    )
    cell_head = ParagraphStyle(
        "ReportCellHead",
        parent=cell,
        fontName=_BOLD_FONT,
        textColor=colors.white,
    )

    def p(text, style):
        return Paragraph(_arabic(str(text)), style)

    document = SimpleDocTemplate(
        stream,
        pagesize=A4,
        topMargin=40 * mm,
        bottomMargin=25 * mm,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        title=str(_doc_title()),
        author="SchoolPlatform",
    )

    elements = []

    title_text = title or _doc_title()
    elements.append(p(title_text, h1))

    institution_name = institution or _("School Platform")
    meta_lines = " | ".join(
        part for part in (
            _arabic(institution_name),
            _arabic(user_name),
            now.strftime("%Y-%m-%d %H:%M"),
        ) if part
    )
    elements.append(p(meta_lines, sub))

    files = files or []

    if files:
        elements.append(p(_("Files ({count})").format(count=len(files)), h2))

        table_data = [
            [
                p(_("File name"), cell_head),
                p(_("Type"), cell_head),
                p(_("Size"), cell_head),
            ]
        ]

        for item in files:
            table_data.append(
                [
                    p(item.get("name", ""), cell),
                    p(_status_badge_label(item.get("kind", "other")), cell),
                    p(human_size(item.get("size", 0)), cell),
                ]
            )

        table = Table(
            table_data,
            colWidths=[90 * mm, 35 * mm, 35 * mm],
            repeatRows=1,
        )
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), BRAND),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, LINE),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BG]),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        elements.append(table)

        elements.append(p(_("Document contents"), h2))

        for item in files:
            name = item.get("name", "")
            kind = item.get("kind", "other")
            excerpt_text = (item.get("excerpt") or "").strip()

            elements.append(
                p(f"{name}  ({_status_badge_label(kind)})", h2)
            )

            if excerpt_text:
                elements.append(p(excerpt_text, excerpt))
            else:
                elements.append(
                    p(_("No extractable text content for this file."), body)
                )

            elements.append(Spacer(1, 3 * mm))

    if notes and str(notes).strip():
        elements.append(p(_("Assistant analysis"), h2))
        elements.append(p(str(notes), body))

    elements.append(Spacer(1, 6 * mm))
    elements.append(
        p(
            _("This report was generated automatically by the SchoolPlatform "
              "AI assistant."),
            sub,
        )
    )

    document.build(elements, onFirstPage=_on_page, onLaterPages=_on_page)

    return document
