# Generated by Django 6.0.7 on 2026-08-16 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_message_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(help_text='The uploaded document or image.', upload_to='assistant/%Y/%m/%d/')),
                ('kind', models.CharField(choices=[('pdf', 'PDF document'), ('docx', 'Word document'), ('xlsx', 'Excel spreadsheet'), ('text', 'Text file'), ('image', 'Image'), ('other', 'File')], default='other', max_length=10)),
                ('size', models.PositiveIntegerField(default=0, help_text='File size in bytes.')),
                ('text', models.TextField(blank=True, default='', help_text='Extracted text used for summarization and Q&A.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assistant.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant attachment',
                'verbose_name_plural': 'Assistant attachments',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
